### ISSUE TITLE
Error: 'core-extensions.h' file not found

### ISSUE THREAD

**Issue by zipme** [KristopherGBaker/libcmark_gfm#1]
After installing via cocoapods, I got this error:  'core-extensions.h' file not found

Any idea what went wrong?

Thanks!

**Comment by KristopherGBaker** [comment]
Hi @zipme 

What's your cocoapods version? Xcode version?

Can you provide an example of your Podfile?

Thanks

**Comment by zipme** [comment]
Hi @KristopherGBaker thanks for the quick reply! 

I tried creating a new project with the same Podfile and it compiles without any errors, so I suspect somewhere in the build settings causes the problem, still investigating, let you know when I find something!
